application:
  host: 0.0.0.0
database:
  require_ssl: false

email_client:
  base_url: https://api.mailgun.net/v3/sandboxeddff7d118394e24bebb8990b9ff352d.mailgun.org
  sender_email: sandboxeddff7d118394e24bebb8990b9ff352d.mailgun.org
